CREATE TABLE IF NOT EXISTS CLIENTE (
	id INT PRIMARY KEY AUTO_INCREMENT, 
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL, 
    rg VARCHAR(15) UNIQUE NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    endereco VARCHAR(100) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONTA (
	id INT PRIMARY KEY AUTO_INCREMENT,
    numero INT UNIQUE NOT NULL,
    saldo DECIMAL(10, 2) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    cliente_id INT,
    FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id) ON DELETE CASCADE,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONTA_CORRENTE (
	conta_id INT PRIMARY KEY,
    limite DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (conta_id) REFERENCES CONTA(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CONTA_INVESTIMENTO (
	conta_id INT PRIMARY KEY,
    montante_minimo DECIMAL(10, 2) NOT NULL,
    deposito_minimo DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (conta_id) REFERENCES CONTA(id) ON DELETE CASCADE
);